services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:homolog
    restart: always
    depends_on:
      - redis
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

volumes:
  evolution_instances:
  evolution_redis:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
